version: '3.3'
services:
    database:
        ports:
            - '5433:5432'
        environment:
            - POSTGRES_PASSWORD=1234
        image: 'postgres:12.2'

    webapp:
      build: .
      ports:
        - '5000:5000'
      depends_on:
        - database
