version: '3.3'
services:

    web:
      build: .
      ports:
        - 5001:5000
      depends_on:
        - postgres

    postgres:
        ports:
            - '5433:5432'
        container_name: biblio
        environment:
            - POSTGRES_PASSWORD=1234
        image: 'postgres:12.2'